### ISSUE TITLE
Bad Request without description when campaign is not found

### ISSUE THREAD

**Issue by mangelsnc** [WorldCoo/docs-slate-api#1]
I have noticed that when I perform a POST request to add a donation with a fake `campaing_id` the response is a 400 Bad Request.

This is not bad as itself, but the `fields` property of the response is empty, and there's not description of what is wrong. Something like "Campaign ID not found" or "Campaign disabled" will help.

In my case, the wrong ID comes from a typo.

I report this here because I don't found a better place to do it.

**Comment by AitorGuerrero** [comment]
I've fix the issue, thank you so much for the feedback.
